### PR TITLE
Add warn option

### PR DESCRIPTION
**Pull request by aaronjensen**
I'd like to not fail the build while there are flow errors for rapid iteration, but I still want to see them.

### CODE REVIEW

**Comment by aaronjensen** [comment]
That build failure looks unrelated afaict

**Comment by happylynx** [comment]
Hi @aaronjensen, thank you for the pull. Isn't the desired behavior - to emit files regardless of flow error - the default behavior? It is supposed to be controlled by option `failOnError` which is `false` by default. As shown in second screenshot in `README.md` in case of error assets are still emitted. What does `failOnError` option for you?

**Comment by happylynx** [comment]
> That build failure looks unrelated afaict

Yes, CI is broken

**Comment by aaronjensen** [comment]
From the code, it looks like `failOnError` would just prevent the compile, but because it adds errors to the compilation regardless of whether or not `failOnError` is set, the compile actually fails which means that hot updates do not happen when running webpack-dev-server.

**Comment by happylynx** [comment]
It was reworked into `reportingSeverity` option.

**Comment by aaronjensen** [comment]
That looks great, thank you!

**Comment by aaronjensen** [comment]
btw, would you mind pinging me here when you drop a new release? Thanks!

**Comment by happylynx** [comment]
Released as part of v. 1.2.0. Thank you for contributing.

**Pull request closed without merging**
